server {
	listen 80 default_server;
	listen 443 ssl;
	serverName	template.com;
	root	/PATH/TO/FOLDER;
	allowedMethods GET POST DELETE;
	cgiAllowed yes;
	clientMaxBodySize	1M;
	errorPage	404 error/404.html 405 error/405.html;
	index	index.php index.html index.htm;
	autoIndex on;
	# return?;
	#host?
}